[package]
name = "audio-spectrum-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
hound = "3.5.1"
image = "0.25.9"
indicatif = "0.18.4"
rustfft = "6.4.1"
symphonia = { version = "0.5", features = ["mp3"] }
